package com.example.domain

import com.example.data.model.PhishingAnalysisResult
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object SecurityReportExporter {

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss z", Locale.US)

    fun generateTextReport(result: PhishingAnalysisResult): String {
        val dateStr = dateFormat.format(Date(result.scannedAt))

        return buildString {
            appendLine("=======================================================")
            appendLine("             NO PHISH 2.0 SECURITY AUDIT REPORT        ")
            appendLine("=======================================================")
            appendLine("Target URL:      ${result.url}")
            appendLine("Timestamp:       $dateStr")
            appendLine("Risk Score:      ${result.riskScore}/100")
            appendLine("Verdict:         ${result.status.uppercase()}")
            appendLine("-------------------------------------------------------")
            appendLine("1. EXECUTIVE SUMMARY & EXPLANATION")
            appendLine(result.userExplanation.ifBlank { "No explanation available." })
            appendLine()
            appendLine("-------------------------------------------------------")
            appendLine("2. ACTIONABLE SECURITY RECOMMENDATION")
            appendLine(
                when {
                    result.riskScore >= 76 ->
                        "CRITICAL: LIKELY PHISHING. Do NOT enter credentials, OTPs, PINs, or financial information. Report this URL to your security team or hosting registrar immediately."
                    result.riskScore >= 51 ->
                        "HIGH RISK: Suspicious deceptive indicators detected. Avoid logging in or submitting forms. Verify domain legitimacy directly through official external channels."
                    result.riskScore >= 21 ->
                        "SUSPICIOUS: Moderate anomaly patterns detected. Exercise caution and check URL spelling carefully before proceeding."
                    else ->
                        "LOW RISK: No overt phishing signatures detected. Note: Absence of detected threats does not guarantee absolute safety. Always practice standard cybersecurity hygiene."
                }
            )
            appendLine()
            appendLine("-------------------------------------------------------")
            appendLine("3. MULTI-LAYER TECHNICAL BREAKDOWN")
            appendLine("• URL Structure:       ${result.analysisBreakdown.urlStructure}")
            appendLine("• Brand Impersonation: ${result.analysisBreakdown.brandImpersonation}")
            appendLine("• NLP Urgency Check:   ${result.analysisBreakdown.nlpUrgencyCheck}")
            appendLine("• Whitelist Status:    ${result.analysisBreakdown.whitelistStatus}")
            appendLine()
            appendLine("-------------------------------------------------------")
            appendLine("4. DETECTED THREAT INDICATORS (${result.detectedThreats.size})")
            if (result.detectedThreats.isNotEmpty()) {
                result.detectedThreats.forEach { threat ->
                    appendLine("  [!] $threat")
                }
            } else {
                appendLine("  [✓] No critical threat signatures triggered.")
            }
            appendLine()
            appendLine("-------------------------------------------------------")
            appendLine("5. ENGINE TELEMETRY & RESEARCH SIGNALS")
            appendLine("• ML Probability:      ${"%.2f".format(result.engineTelemetry.mlProbability * 100)}% (Confidence: ${"%.1f".format(result.engineTelemetry.mlConfidence)}%)")
            appendLine("• Shannon Entropy:     ${"%.3f".format(result.engineTelemetry.shannonEntropy)}")
            appendLine("• RAG Similarity:      ${"%.2f".format(result.engineTelemetry.ragCosineSimilarity * 100)}% (Top Match: ${result.engineTelemetry.ragTopMatch ?: "None"})")
            appendLine("• NLP Urgency Score:   ${result.engineTelemetry.nlpUrgencyScore}/100")
            appendLine("• Model Architecture:  ${result.engineTelemetry.modelVersion}")
            appendLine("=======================================================")
            appendLine("Generated by NoPhish 2.0 — Explainable Phishing Platform")
        }
    }
}
