package com.example.domain

import kotlin.math.abs
import kotlin.math.exp
import kotlin.math.roundToInt

data class FeatureContribution(
    val featureName: String,
    val rawValue: Float,
    val contribution: Float,
    val isRiskIndication: Boolean,
    val description: String
)

data class MlInferenceResult(
    val probability: Float,
    val isPhishing: Boolean,
    val confidencePercentage: Float,
    val riskScore: Int,
    val rawLogit: Float,
    val topContributors: List<FeatureContribution>,
    val features: ExtractedUrlFeatures,
    val modelVersion: String = SupervisedUrlClassifier.MODEL_VERSION,
    val modelChecksum: String = SupervisedUrlClassifier.MODEL_CHECKSUM
)

/**
 * Supervised Machine Learning Classifier for URL Phishing Detection.
 *
 * Automatically generated by scripts/train_classifier.py from trained_model.json.
 * Uses L2-regularized Logistic Regression on a 24-dimensional normalized feature space.
 * Normalization parameters and model weights are computed strictly from the 70% training split.
 */
object SupervisedUrlClassifier {

    const val MODEL_VERSION = "v1.1.0-stratified"
    const val MODEL_CHECKSUM = "4cdf75ebeca34bf0"

    // Feature means from training set standardization (ONLY training split)
    val FEATURE_MEANS = floatArrayOf(
        36.80152672f,
        20.96946565f,
        7.97709924f,
        0.24427481f,
        1.27480916f,
        1.41984733f,
        1.29770992f,
        0.00763359f,
        0.01526718f,
        0.01526718f,
        0.00763359f,
        0.50381679f,
        0.21374046f,
        0.01121642f,
        0.52671756f,
        0.01526718f,
        0.21374046f,
        0.01526718f,
        3.42837297f,
        2.18707659f,
        0.42366412f,
        0.75572519f,
        4.74045802f,
        8.48091603f
    )

    // Feature standard deviations from training set standardization (ONLY training split)
    val FEATURE_STDS = floatArrayOf(
        12.36618132f,
        11.69258846f,
        6.16746654f,
        2.78516134f,
        0.69954658f,
        1.51810548f,
        0.60145696f,
        0.08703629f,
        0.17407258f,
        0.12261358f,
        0.08703629f,
        2.27288714f,
        1.33655381f,
        0.04897285f,
        0.49928566f,
        0.12261358f,
        0.60541619f,
        0.12261358f,
        0.52975859f,
        1.25875040f,
        0.49989801f,
        1.06356453f,
        1.89651261f,
        2.37143029f
    )

    // Supervised Model Learned Weights (L2 Regularized Logistic Regression)
    val WEIGHTS = floatArrayOf(
        0.40213302f,  // urlLength
        0.38288227f,  // hostLength
        0.18078912f,  // pathLength
        0.00833244f,  // queryLength
        -0.12046640f,  // dotCount
        0.83473727f,  // hyphenCount
        -0.67579300f,  // slashCount
        0.00833244f,  // questionMarkCount
        0.00833244f,  // equalCount
        -0.10815163f,  // atSymbolCount
        0.00833244f,  // ampersandCount
        0.07662896f,  // digitCount
        0.24513830f,  // hostDigitCount
        0.05270722f,  // digitRatio
        -1.37315350f,  // isHttps
        0.24414089f,  // isIpAddress
        -0.07507211f,  // subdomainCount
        0.06951533f,  // hasCustomPort
        0.10715710f,  // hostEntropy
        0.30581463f,  // pathEntropy
        0.68724558f,  // tldAbuseRisk
        0.52217495f,  // phishingKeywordCount
        0.52572649f,  // tokenCount
        0.14334836f  // longestTokenLength
    )

    // Model Learned Bias
    const val BIAS = -0.01144894f

    private fun sigmoid(z: Float): Float {
        return when {
            z < -20.0f -> 0.0f
            z > 20.0f -> 1.0f
            else -> (1.0f / (1.0f + exp(-z)))
        }
    }

    private fun describeFeatureContribution(name: String, rawValue: Float, contribution: Float): String {
        return when (name) {
            "isHttps" -> if (rawValue > 0.5f) "Valid HTTPS encryption protocol (-${abs(contribution).let { "%.2f".format(it) }} logit reduction)" else "Unencrypted plain HTTP scheme (Risk amplification)"
            "hyphenCount" -> "Hyphen stuffing (${rawValue.toInt()} hyphens in domain, +${"%.2f".format(contribution)} logit)"
            "tldAbuseRisk" -> if (rawValue > 0.5f) "High-abuse TLD flagged in registry (+${"%.2f".format(contribution)} logit)" else "Standard or institutional TLD"
            "phishingKeywordCount" -> "Security/lure keyword count: ${rawValue.toInt()} detected (+${"%.2f".format(contribution)} logit)"
            "tokenCount" -> "High subdomain / token segmentation (${rawValue.toInt()} tokens, +${"%.2f".format(contribution)} logit)"
            "isIpAddress" -> if (rawValue > 0.5f) "Raw IP host bypassing DNS naming (+${"%.2f".format(contribution)} logit)" else "Standard DNS hostname"
            "hostEntropy" -> "Host Shannon entropy: ${"%.2f".format(rawValue)} bits (DGA variance: +${"%.2f".format(contribution)})"
            "pathEntropy" -> "Path entropy: ${"%.2f".format(rawValue)} bits (+${"%.2f".format(contribution)})"
            "hostDigitCount" -> "Numerical digits in host: ${rawValue.toInt()} (+${"%.2f".format(contribution)})"
            "urlLength" -> "URL length: ${rawValue.toInt()} chars (+${"%.2f".format(contribution)})"
            else -> "$name: $rawValue (contribution: ${"%.2f".format(contribution)})"
        }
    }

    /**
     * Executes supervised inference on a URL.
     */
    fun predict(url: String): MlInferenceResult {
        val features = UrlFeatureExtractor.extract(url)
        return predictFeatures(features)
    }

    fun predictFeatures(features: ExtractedUrlFeatures): MlInferenceResult {
        val vector = features.vector
        var logit = BIAS
        val contributions = mutableListOf<FeatureContribution>()

        for (i in vector.indices) {
            val mean = FEATURE_MEANS[i]
            val std = if (FEATURE_STDS[i] > 1e-6f) FEATURE_STDS[i] else 1.0f
            val standardized = (vector[i] - mean) / std
            val contribution = WEIGHTS[i] * standardized
            logit += contribution

            contributions.add(
                FeatureContribution(
                    featureName = UrlFeatureExtractor.FEATURE_NAMES[i],
                    rawValue = vector[i],
                    contribution = contribution,
                    isRiskIndication = contribution > 0.1f,
                    description = describeFeatureContribution(
                        UrlFeatureExtractor.FEATURE_NAMES[i],
                        vector[i],
                        contribution
                    )
                )
            )
        }

        val probability = sigmoid(logit)
        val isPhishing = probability >= 0.5f
        val confidence = (abs(probability - 0.5f) * 2.0f * 100.0f).coerceIn(0.0f, 100.0f)
        val riskScore = (probability * 100.0f).roundToInt().coerceIn(0, 100)

        // Sort by absolute contribution impact
        val sortedContributions = contributions.sortedByDescending { abs(it.contribution) }

        return MlInferenceResult(
            probability = probability,
            isPhishing = isPhishing,
            confidencePercentage = confidence,
            riskScore = riskScore,
            rawLogit = logit,
            topContributors = sortedContributions.take(6),
            features = features,
            modelVersion = MODEL_VERSION,
            modelChecksum = MODEL_CHECKSUM
        )
    }
}
